### ISSUE TITLE
Mutation to create order with subscription?

### ISSUE THREAD

**Issue by jacobdubail** [wp-graphql/woographql-subscriptions#4]
I realize this is less of an issue and more of a question. I'm not seeing any details in the readme or any other guides outlining how to create subscriptions via WP GraphQL. I have this extension installed and activated, along with WooCommerce, WC Subscriptions, WooGraphQL, and WPGraphQL. Any guidance you anyone can offer is greatly appreciated.

**Comment by jacobdubail** [comment]
for some reason, having an existing subscription of a different product prevented the new subscription creation. resolved.

**Comment by aresrioja10** [comment]
Hi @jacobdubail,

How can I create a subscription?
